// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numOfsequence = Integer.parseInt(args[0]);
		int counter = 0;
		int lessThanhalf = 0;
		int moreThanhalf = 0;
		double randomVar = 0;
		double ratio;
		while (counter < numOfsequence) {
			randomVar = Math.random();
			if (randomVar <= 0.5) {
				lessThanhalf ++;	
			}
			else { 
				moreThanhalf++;
			}
			counter++;
		}
		System.out.println("> 0.5: "+ moreThanhalf + " times");
		System.out.println("<= 0.5: "+ lessThanhalf + " times");
		if (moreThanhalf >= 1 && lessThanhalf >= 1) {
			ratio = (double)Math.min(moreThanhalf,lessThanhalf)/Math.max(moreThanhalf,lessThanhalf);
			System.out.println("Ratio: " + ratio);
		}		
		
	}
}
